spring.application.name=EmployeeManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/employeemanagementdb
spring.datasource.username=postgres
spring.datasource.password=1034
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 24 hours
token.expiration.access=86400000
# 7 days
token.expiration.refresh=604800000
token.secret-key=vpwGiG8Hh659YkRNBnBZIP1a6pRWSfLBKyd4f4MigA8

springdoc.api-docs.enabled=true

cors.allowedHeaders =  [ "Accept", "Accept-Language","Origin","Content-Type","Authorization" ]
cors.allowedOrigins = [ "*" ]
cors.allowedMethods = [ "GET","POST","DELETE","PUT" ,"PATCH","OPTIONS" ,"HEAD" ]
cors.urlPattern = "/**"
cors.allowCredentials = true

project.host=localhost
server.port=8080